### ISSUE TITLE
Supervisor Comments

### ISSUE THREAD

**Issue by casmith51** [TnTech-ECE/CapstoneStarterRepo#18]
**Is your feature request related to a problem? Please describe.**
This one is more delicate to handle.   I do want it to be known however.  The discrepancy in expectation from team to team felt too great.  The professor of the class was not guaranteed to be a team's supervisor.  This introduces slight bit of "luck" as to what quality of work is expected from a team.   Personally, it is my belief that my team received completely justified criticism and were expected to deliver appropriate levels of quality work.  In doing this, I did produce higher quality work that I can be more proud of.  However, in terms of grading, it can feel entirely unfair when shown another team's work that was accepted be of less effort/quality than our own which was rejected.

**Describe the solution you'd like**
It is quite hard to say what should be done here.  The most fair solution for the students would be that the professor is the only supervisor to ensure that the Capstone experience has at least one less variable to worry about.  This can also be bad for the supervisor though.  Having one supervisor oversee so many projects of such a wide variety would be a daunting task.  It would also be unfair to the other faculty who have good ideas for Capstone projects and enjoy working with the teams.  

**Describe alternatives you've considered**
Our supervisor kept meticulous notes from our weekly meetings.  The supervisor recorded who was present, what was said, and what was planned.  This is actually very handy to have recorded.  I am not certain that any other supervisor did this, but looking back, asking that each supervisor do this and then submit this to the professor would give additional insight into each team's status.  The supervisor could also use these notes to exchange recommended courses of action with the professor to steer a team back on course or keep them on the right track.

**Comment by JesseTNRoberts** [comment]
The discrepancy may have been felt, but it was not realized. I ensure that.
