### ISSUE TITLE
Combining Date-Based Grading and Team Evaluations in Each Milestone

### ISSUE THREAD

**Issue by kesternucum** [TnTech-ECE/CapstoneStarterRepo#20]
**Is your feature request related to a problem? Please describe.**
Although I do believe that date-based grading is an effective grading system that simulates what it is like when deadlines are missed in the real-world (yes, projects often take longer than predicted but deadlines cannot be passed without any consequences), I personally feel like it is unfair that if a team member falls behind causing the deadline to be missed and the submission for the milestone to be delayed, then the entire team is penalized just as that student. I'm not 100% sure how it is in industry, but if an engineer in a team is dragging the entire team behind, then I believe that that engineer should be punished rather than the entire team, especially since tasks are delegated to individuals. I know in my team, there were times that certain members had already completed their work by the deadline but it was other teammates that were falling behind, causing the entire team to be penalized in points. I personally feel like it is more fair to penalize the teammates identified as being the ones who are causing the delay more heavily than those who have already finished their contributions.

**Describe the solution you'd like**
I would revise the grading for each milestone and allocate the 16 points on the final grade dedicated for team evaluations into the four major milestones (detailed design, ordering completed, prototype, and experimentation), where each milestone would have four more points to that grade (detailed design has total of 12 points, ordering complete has total of 14 points, prototype has 18 points, and experimental analysis has 16 points). For each milestone, the grade would be evenly split into two subsections, one being the date-based grading and the other being the team evaluation. After each milestone (and for detailed design and ordering completed, the same evaluation can be used for both milestones), a survey will be sent out like the CATME, but team members are encouraged to indicate if there are any specific members who contributed toward any delays in the final submission of the milestone. For example, if Ann finished her work on time but Bob kept procrastinating until 5 days after the deadline to finish his detailed design, then they will still both receive the same grade on the portion for date-based grading (since the actions of one member on the team affect all members of the team), but if Ann indicates that Bob was the reason why and that she did her best to help Bob and push him to finish, then Ann should get full credit (or close enough) for the team evaluation section and Bob should be more penalized for it. This solution would balance the effects of one dragging team member so that the team members who are performing better are not penalized the same as those who are pulling everyone else down.

**Describe alternatives you've considered**
Another alternative would be to scale the date-based grading based on team evaluations. So if the team receives a certain grade on the date-based grading, team members would receive a percentage of that grade based on their contributions. This alternative would also allow for other team members who had to pick up the slack of others to penalize those who didn't do much work. So even if a team were to receive a 100 but a team member did not contribute effectively, then that team member (as long as the teammates indicate this) will not receive full marks.

**Comment by JesseTNRoberts** [comment]
This does not accomplish the same thing. This is not really a solution to a problem. The solution to the problem mentioned is for the team to act as a team rather than lone wolves.
